[package]
name = "parse_argument"
version = "0.1.3"
edition = "2021"
description = "A simple way to deal with taking in commandline arguments"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
